// src/components/Header.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import { Gamepad2 } from 'lucide-react';

const navLinks = [
  { href: '/', label: 'Home' },
  { href: '/portfolio', label: 'Portfolio' },
  { href: '/blog', label: 'Blog' },
  { href: '/about', label: 'About' },
  { href: '/contact', label: 'Contact' },
];

export default function Header() {
  const pathname = usePathname();

  return (
    <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-14 items-center">
        <Link href="/" className="mr-6 flex items-center space-x-2">
          <Gamepad2 className="h-6 w-6 text-primary glow-primary" />
          <span className="font-bold font-headline sm:inline-block">
            Portfolio Quest
          </span>
        </Link>
        <nav className="flex flex-1 items-center space-x-6 text-sm font-medium">
          {navLinks.map(({ href, label }) => (
            <Link
              key={href}
              href={href}
              className={cn(
                'transition-colors hover:text-primary',
                pathname.startsWith(href) && href !== '/' || pathname === href ? 'text-primary font-semibold' : 'text-muted-foreground'
              )}
            >
              {label}
            </Link>
          ))}
        </nav>
      </div>
    </header>
  );
}

// src/components/Header.vue
<template>
  <header class="bg-gray-900 text-white shadow-md">
    <nav class="container mx-auto flex justify-between items-center py-4">
      <div class="text-2xl font-bold pl-8 md:pl-20">DevGame Portfolio</div>
      <ul class="flex space-x-8 pr-8 md:pr-20">
        <li>
          <router-link to="/" class="hover:text-yellow-400 transition-colors duration-200"
            >Trang chủ</router-link
          >
        </li>
        <li>
          <router-link
            to="/projects"
            class="hover:text-yellow-400 transition-colors duration-200"
            >Dự án</router-link
          >
        </li>
        <li>
          <router-link
            to="/cv"
            class="hover:text-yellow-400 transition-colors duration-200"
            >CV</router-link
          >
        </li>
        <li>
          <router-link
            to="/blog"
            class="hover:text-yellow-400 transition-colors duration-200"
            >Blog</router-link
          >
        </li>
        <li>
          <router-link
            to="/contact"
            class="ml-2 bg-yellow-400 text-gray-900 font-semibold px-4 py-2 rounded-full shadow hover:bg-yellow-500 transition"
          >
            Liên hệ
          </router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script setup>
// Để trống, có thể thêm logic sau
</script>

<style scoped>
/* Tuỳ chỉnh thêm nếu cần */
</style>
